// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkCFH_iUIGD1HQ3tu46FC1jPjG-astsv0',
    appId: '1:496228848572:web:57af509f56515b5804d1b9',
    messagingSenderId: '496228848572',
    projectId: 'musicplayerpersonal',
    authDomain: 'musicplayerpersonal.firebaseapp.com',
    storageBucket: 'musicplayerpersonal.appspot.com',
    measurementId: 'G-LPCG030P71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbS0Y1ZBskLPHeKufbB-i9cO5_oIJcCHg',
    appId: '1:496228848572:android:92826d4f280ec67d04d1b9',
    messagingSenderId: '496228848572',
    projectId: 'musicplayerpersonal',
    storageBucket: 'musicplayerpersonal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0rFDlXmDaFZ6syE4RsvD-Q83NSTU_gMM',
    appId: '1:496228848572:ios:b3add5000cd6831e04d1b9',
    messagingSenderId: '496228848572',
    projectId: 'musicplayerpersonal',
    storageBucket: 'musicplayerpersonal.appspot.com',
    iosBundleId: 'com.example.musicPlayerPersonal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0rFDlXmDaFZ6syE4RsvD-Q83NSTU_gMM',
    appId: '1:496228848572:ios:f53e8c53f9f56afc04d1b9',
    messagingSenderId: '496228848572',
    projectId: 'musicplayerpersonal',
    storageBucket: 'musicplayerpersonal.appspot.com',
    iosBundleId: 'com.example.musicPlayerPersonal.RunnerTests',
  );
}
